parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $asciiArtPath: '%kernel.project_dir%/src/Resource/ascii/'
            $openAiToken: '%env(OPEN_AI_TOKEN)%'

    Symfony\Component\Console\Terminal:
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\:
        resource: '../src/Command/*Command.php'
        tags: ['console.command']